# Generated by Django 4.0.3 on 2022-03-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduleit', '0002_alter_schedule_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scheduletype',
            name='end_time',
            field=models.TimeField(choices=[('EARLY_START', '00:00:00'), ('EARLY_END', '08:00:00'), ('REGULAR_START', '08:00:00'), ('REGULAR_END', '16:00:00'), ('LATE_START', '16:00:00'), ('LATE_END', '23:59:00')]),
        ),
        migrations.AlterField(
            model_name='scheduletype',
            name='start_time',
            field=models.TimeField(choices=[('EARLY_START', '00:00:00'), ('EARLY_END', '08:00:00'), ('REGULAR_START', '08:00:00'), ('REGULAR_END', '16:00:00'), ('LATE_START', '16:00:00'), ('LATE_END', '23:59:00')]),
        ),
    ]
